server:
  port: 8801
  servlet:
    context-path: /alibaba

# 日志配置
logging:
  level:
    org.springframework: info
    com.narc: info
    additivity: false
  file: ./logs/alibaba.log
  file.max-size: 100MB
